"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b6=qu_!)3tkh1pcqe75b#u0rz(jp115)sna@e&@9wy=)bc51f='

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production for security
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Allowed hosts for production
ALLOWED_HOSTS = [
    'backend.tmfouzy.sg',
    'www.backend.tmfouzy.sg',
    'localhost',
    '127.0.0.1',
    '192.168.100.13',  # Your local IP for mobile testing
    '*',  # Allow all for development
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For collectstatic command
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (for OTP)
# SMTP Configuration for website@hajj.tmfouzy.sg
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.hajj.tmfouzy.sg')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True  # Port 587 uses TLS
EMAIL_USE_SSL = False  # TLS is used instead of SSL for port 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'website@hajj.tmfouzy.sg')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'website@hajj.tmfouzy.sg')
SERVER_EMAIL = os.getenv('EMAIL_HOST_USER', 'website@hajj.tmfouzy.sg')

# For testing, uncomment below to print to console instead:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",  # Expo dev server
    "http://192.168.100.13:8081",  # Expo on local network
    "https://tmfouzy.sg",
    "https://www.tmfouzy.sg",
    "http://tmfouzy.sg",
    "http://www.tmfouzy.sg",
    "https://8606-223-123-125-222.ngrok-free.app",  # Ngrok frontend URL
]

# Allow all origins for development (mobile app testing)
CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials for CORS
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for production
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12
}


# ==========================================
# LIVE AUDIO STREAMING CONFIGURATION
# ==========================================

# Agora.io Configuration
# Sign up at: https://www.agora.io/
# Get App ID and App Certificate from Agora Console
AGORA_APP_ID = os.getenv('AGORA_APP_ID', '')
AGORA_APP_CERTIFICATE = os.getenv('AGORA_APP_CERTIFICATE', '')

# Firebase Cloud Messaging (Push Notifications)
# Get Server Key from: Firebase Console > Project Settings > Cloud Messaging
FCM_SERVER_KEY = os.getenv('FCM_SERVER_KEY', '')

# Validate Live Audio Configuration
if not AGORA_APP_ID:
    print('⚠️  WARNING: AGORA_APP_ID not configured. Live audio streaming will not work.')
if not AGORA_APP_CERTIFICATE:
    print('⚠️  WARNING: AGORA_APP_CERTIFICATE not configured. Live audio streaming will not work.')
if not FCM_SERVER_KEY:
    print('⚠️  WARNING: FCM_SERVER_KEY not configured. Push notifications will not work.')
