# Generated by Django 5.2 on 2026-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_image_alter_package_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsharingprice',
            name='sharing_type',
            field=models.CharField(choices=[('single', 'Single (1 Adult)'), ('double', 'Double Sharing (2 Adults)'), ('triple', 'Triple Sharing (3 Adults)'), ('quad', 'Quad Sharing (4 Adults)')], max_length=20),
        ),
    ]
