# Generated by Django 5.2 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_roomsharingprice_sharing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='child_price_percentage',
            field=models.DecimalField(decimal_places=2, default=75, help_text='Percentage of adult price for children (e.g., 75 = 75%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='package',
            name='infant_price_percentage',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Percentage of adult price for infants (e.g., 25 = 25%)', max_digits=5),
        ),
    ]
