# Generated by Django 5.2 on 2026-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_package_child_price_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='payment_screenshot',
            field=models.URLField(blank=True, help_text='Payment proof screenshot URL'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=models.URLField(blank=True, help_text='Payment proof screenshot URL'),
        ),
    ]
