# Generated by Django 5.2 on 2026-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemorder_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='Payment proof screenshot (image/PDF)', null=True, upload_to='order_screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='Payment proof screenshot (image/PDF)', null=True, upload_to='payment_screenshots/'),
        ),
    ]
