# Generated by Django 5.2 on 2026-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_itemorder_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='child_price_percentage',
        ),
        migrations.AddField(
            model_name='package',
            name='child_no_bed_price_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentage of adult price for child (no bed) (e.g., 100 = 100%)', max_digits=5),
        ),
    ]
