# Generated by Django 5.2 on 2026-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, help_text='Booking remarks for invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, help_text='Payment remarks for invoice'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='Payment proof screenshot (image/PDF) - Cannot be changed once uploaded', null=True, upload_to='order_screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('paynow', 'PayNow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='Payment proof screenshot (image/PDF) - Cannot be changed once uploaded', null=True, upload_to='payment_screenshots/'),
        ),
    ]
