# Generated by Django 5.2 on 2026-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_booking_remarks_payment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='complimentary_items',
            field=models.TextField(blank=True, help_text='Free gifts/items included with package (e.g., Prayer mat, Zamzam bottle, Ihram set)'),
        ),
    ]
