# Generated by Django 5.2 on 2026-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_package_complimentary_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_capacity',
            field=models.IntegerField(default=50, help_text='Maximum number of passengers for this package'),
        ),
    ]
