# Generated by Django 5.2 on 2026-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_package_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shipping_country',
            field=models.CharField(blank=True, default='Singapore', max_length=100),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shipping_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
