# Generated by Django 5.2 on 2026-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_itemorder_shipping_city_itemorder_shipping_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tour_leader_email',
            field=models.EmailField(blank=True, default='', help_text='Tour leader email address', max_length=254),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_leader_name',
            field=models.CharField(blank=True, default='', help_text='Name of the tour leader/guide', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_leader_phone',
            field=models.CharField(blank=True, default='', help_text='Tour leader contact number', max_length=20),
        ),
    ]
