# Generated by Django 5.2 on 2026-03-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_package_tour_leader_email_package_tour_leader_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tour_leader_email',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tour_leader_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tour_leader_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_tour_leader',
            field=models.BooleanField(default=False, help_text='Mark this customer as a tour leader'),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_leader',
            field=models.ForeignKey(blank=True, help_text='Select a customer marked as tour leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_packages', to='api.customer'),
        ),
    ]
