# Generated by Django 5.2 on 2026-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_package_tour_leader_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hotel_country',
            field=models.CharField(blank=True, default='', help_text='Country where hotel is located', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_image',
            field=models.URLField(blank=True, help_text='Hotel image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_name',
            field=models.CharField(blank=True, default='', help_text='Name of the hotel', max_length=300),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_star_rating',
            field=models.IntegerField(blank=True, help_text='Hotel star rating (1-5)', null=True),
        ),
    ]
