# Generated by Django 5.2 on 2026-03-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_package_hotel_country_package_hotel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(help_text='Icon name from @expo/vector-icons', max_length=100)),
                ('icon_type', models.CharField(default='MaterialCommunityIcons', help_text='Icon library (MaterialCommunityIcons, Ionicons, FontAwesome5)', max_length=50)),
                ('color', models.CharField(default='#2e7d32', help_text='Hex color code', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dua Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DuaSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('has_rounds', models.BooleanField(default=False, help_text='True if this subcategory has rounds (like Tawaf)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.duacategory')),
            ],
            options={
                'verbose_name_plural': 'Dua Sub-Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DuaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., First Round, Second Round', max_length=200)),
                ('round_number', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.duasubcategory')),
            ],
            options={
                'ordering': ['order', 'round_number'],
                'unique_together': {('subcategory', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('arabic_text', models.TextField(help_text='Arabic text of the dua')),
                ('transliteration', models.TextField(help_text='Romanized pronunciation')),
                ('translation', models.TextField(help_text='English translation')),
                ('description', models.TextField(help_text='Context or when to recite this dua')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(blank=True, help_text='For duas that belong to a specific round', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='api.duaround')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='api.duasubcategory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
