# Generated by Django 5.2 on 2026-03-08 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_duacategory_duasubcategory_duaround_dua'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('visa', 'Visa'), ('ticket', 'Flight Ticket'), ('hotel', 'Hotel Voucher'), ('itinerary', 'Travel Itinerary'), ('insurance', 'Travel Insurance'), ('vaccination', 'Vaccination Certificate'), ('passport', 'Passport Copy'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text="Document title (e.g., 'Saudi Visa', 'Flight Ticket - SQ123')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the document')),
                ('file', models.FileField(help_text='Upload PDF, image, or document file', upload_to='customer_documents/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important/urgent document')),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Optional: Link to specific booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Staff member who uploaded this', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
    ]
