# Generated by Django 5.2.11 on 2026-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_itinerary_json_child_with_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='Day-by-day itinerary as JSON array: [{"day":1,"date":"","title":"","description":""}]'),
        ),
    ]
